# What is tensor?


1. Tensor is a concept of array in pytorch
2. It can support GPU
3. Tensor can be vector, array or n-dimension array



# How to create a tensor?

In [2]:
import torch

In [20]:
# 0 維 tensor
t0 = torch.tensor(1,dtype=torch.int32)

print('t0:　',t0.shape)
print(t0)
print('---------')

# 1 維 tensor
t1 = torch.tensor([1,2,3],dtype=torch.float16)
print('t1:　',t1.shape)
print(t1)
print('---------')

# 2 維 tensor
t2 = torch.tensor([[1,2,3,4],[6,7,8,9]],dtype=torch.float16)
print('t2:　',t2.shape)
print(t2)
print('---------')

# 3 維 tensor
t3 = torch.tensor([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]],dtype=torch.float16)
print('t3:　',t3.shape)
print(t3)

t0:　 torch.Size([])
tensor(1, dtype=torch.int32)
---------
t1:　 torch.Size([3])
tensor([1., 2., 3.], dtype=torch.float16)
---------
t2:　 torch.Size([2, 4])
tensor([[1., 2., 3., 4.],
        [6., 7., 8., 9.]], dtype=torch.float16)
---------
t3:　 torch.Size([2, 2, 3])
tensor([[[1., 2., 3.],
         [3., 4., 5.]],

        [[5., 6., 7.],
         [7., 8., 9.]]], dtype=torch.float16)


In [28]:
'''
torch.randn: 由平均值為0，標準差為1的常態分佈中，抽樣元素組成給定形狀的張量
參數: size
'''
t4 = torch.randn([2,3])
print(t4)

'''
torch.randint: 在給定的上下界(預設下界為0)中抽樣"整數"元素組成給定形狀的張量
參數: low, high, size
'''
t5 = torch.randint(low=0, high=10, size=(3,2))
print(t5)

'''
torch.ones: 產生給定形狀，元素全為1的張量
參數: size
'''
t6 = torch.ones((2,4))
print(t6)

'''
torch.ones_like: 產生與給定張量相同形狀，但元素全為1的張量
'''
t7 = torch.ones_like(t6)
print(t7)



tensor([[ 0.7006, -0.3608,  1.4482],
        [-0.5746, -0.8766, -1.2984]])
tensor([[1, 0],
        [4, 0],
        [3, 9]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


# array to tensor

In [30]:
import numpy as np

# 產生numpy ndarray
x = np.array([[1.,2],[3,4]])
print(x)

# 由numpy ndarray產生pytorch tensor
y = torch.from_numpy(x)
# y = torch.tensor(x) 也可以達到同樣效果
print(y)

[[1. 2.]
 [3. 4.]]
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


# tensor to array


In [31]:
z = y.numpy()
print(z)

[[1. 2.]
 [3. 4.]]


# tensor運算

In [35]:
# 創建tensor
a = torch.randn((2,3))
b = torch.randn(3)
print(a.shape, b.shape)
print(a)
print(b)

# 相加
t_add1 = a + b
t_add2 = torch.add(a,b)
print(t_add1.shape, t_add2.shape)


# 相減
t_sub1 = a - b
t_sub2 = torch.sub(a,b)
print(t_sub1, t_sub2)


# 相除
t_div1 = a / b
t_div2 = torch.div(a,b)
print(t_div1, t_div2)


# 相乘
t_mul1 = a * b
t_mul2 = torch.mul(a, b)
print(t_mul1, t_mul2)


torch.Size([2, 3]) torch.Size([3])
tensor([[ 0.1585,  0.8403, -1.8294],
        [ 0.2109, -1.2044, -0.1296]])
tensor([-0.6105,  0.1304, -1.8276])
torch.Size([2, 3]) torch.Size([2, 3])
tensor([[ 0.7690,  0.7099, -0.0018],
        [ 0.8213, -1.3348,  1.6980]]) tensor([[ 0.7690,  0.7099, -0.0018],
        [ 0.8213, -1.3348,  1.6980]])
tensor([[-0.2597,  6.4440,  1.0010],
        [-0.3454, -9.2359,  0.0709]]) tensor([[-0.2597,  6.4440,  1.0010],
        [-0.3454, -9.2359,  0.0709]])
torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[-0.0968,  0.1096,  3.3434],
         [-0.1287, -0.1571,  0.2368]]), tensor([[-0.0968,  0.1096,  3.3434],
         [-0.1287, -0.1571,  0.2368]]))

In [37]:
# 矩陣乘法
c = torch.randn((2,3))
d = torch.randn((3,4))

t_matmul1 = c.mm(d)
t_matmul2 = torch.mm(c,d)
t_matmul3 = torch.matmul(c,d)
t_matmul4 = c @ d
t_matmul1

tensor([[ 0.3473, -0.4294, -0.5247, -0.2404],
        [ 0.9603, -0.0496, -1.2464, -1.0502]])

# Tensor shape

In [50]:
# 創健tensor
a = torch.tensor([[[1, 2, 3], [4, 5, 6]],
					[[5, 6, 7], [8, 9, 0]]])
print(a.shape)
print(a)

torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[5, 6, 7],
         [8, 9, 0]]])


In [51]:
# 將tensor形狀由[2,2,3]改為[2,6]
b = a.reshape(2, 6)
c = a.view(2, 6)
d = a.reshape(3, -1)
print(b.shape, c.shape, d.shape)
b,c,d

torch.Size([2, 6]) torch.Size([2, 6]) torch.Size([3, 4])


(tensor([[1, 2, 3, 4, 5, 6],
         [5, 6, 7, 8, 9, 0]]), tensor([[1, 2, 3, 4, 5, 6],
         [5, 6, 7, 8, 9, 0]]), tensor([[1, 2, 3, 4],
         [5, 6, 5, 6],
         [7, 8, 9, 0]]))

In [52]:
# 調換tensor維度
'''
permute 給定輸出的維度順序，如 (0,2,1) 代表輸出的維度順序是原本張量維度的 0,2,1 順序
transpose 將給定維度進行對調，如 (1,2) 將原本的第 1 維與第 2 維進行對調
'''
a.shape
e = a.permute((0, 2, 1))
f = a.transpose(1,2)
print(a.shape, e.shape, f.shape)
a, e, f

torch.Size([2, 2, 3]) torch.Size([2, 3, 2]) torch.Size([2, 3, 2])


(tensor([[[1, 2, 3],
          [4, 5, 6]],
 
         [[5, 6, 7],
          [8, 9, 0]]]), tensor([[[1, 4],
          [2, 5],
          [3, 6]],
 
         [[5, 8],
          [6, 9],
          [7, 0]]]), tensor([[[1, 4],
          [2, 5],
          [3, 6]],
 
         [[5, 8],
          [6, 9],
          [7, 0]]]))

In [56]:
# 增加張量維度
g = torch.unsqueeze(a, dim=0) #增加維度在1的位置
h = torch.squeeze(g) #壓縮為度為1的位置
print(a.shape, g.shape, h.shape)
g, h

torch.Size([2, 2, 3]) torch.Size([1, 2, 2, 3]) torch.Size([2, 2, 3])


(tensor([[[[1, 2, 3],
           [4, 5, 6]],
 
          [[5, 6, 7],
           [8, 9, 0]]]]), tensor([[[1, 2, 3],
          [4, 5, 6]],
 
         [[5, 6, 7],
          [8, 9, 0]]]))